remote_theme: just-the-docs/just-the-docs
# theme: just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark

title: "testuser的空间"

logo: "/assets/img/profile/!!.png"

footer_content: |
    <a href="https://osu.ppy.sh/users/31860102" target="_blank">
    <img src="assets/img/profile/osu.svg" width="24" style="filter: invert(1);">
    </a>

hide_site_footer: false

favicon: "/favicon.ico"
